teams:
  cli-experimental-admins:
    description: admin access to cli-experimental
    members:
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      cli-experimental: admin
  cli-experimental-maintainers:
    description: write access to cli-experimental
    members:
    - liggitt
    privacy: closed
    repos:
      cli-experimental: write
  cli-utils-admins:
    description: admin access to cli-utils
    members:
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      cli-utils: admin
  cli-utils-maintainers:
    description: write access to cli-utils
    members:
    - karlkfi
    - liggitt
    - mortent
    privacy: closed
    repos:
      cli-utils: write
  krew-admins:
    description: admin access to krew
    members:
    - ahmetb
    - chriskim06
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      krew: admin
  krew-maintainers:
    description: write access to krew
    members:
    - ahmetb
    - chriskim06
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      krew: write
  krew-index-admins:
    description: admin access to krew-index
    members:
    - ahmetb
    - chriskim06
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      krew-index: admin
  krew-index-maintainers:
    description: write access to krew-index
    members:
    - ahmetb
    - chriskim06
    - eddiezane
    - soltysh
    privacy: closed
    repos:
      krew-index: write
  kubectl-validate-admins:
    description: admin access to kubectl-validate
    members:
    - alexzielenski
    - apelisse
    - cici37
    privacy: closed
    repos:
      kubectl-validate: admin
  kubectl-validate-maintainers:
    description: write access to kubectl-validate
    members:
    - alexzielenski
    - apelisse
    - cici37
    privacy: closed
    repos:
      kubectl-validate: write
  kustomize-admins:
    description: ""
    members:
    - eddiezane
    - koba1t
    - soltysh
    privacy: closed
    repos:
      kustomize: admin
  kustomize-maintainers:
    description: ""
    members:
      - varshaprasad96
    privacy: closed
    repos:
      kustomize: maintain
