teams:
  ingress-gce-admins:
    description: Admin access to the ingress-gce repo
    members:
    - aojea
    - bowei
    - thockin
    privacy: closed
    repos:
      ingress-gce: admin
  ingress-gce-maintainers:
    description: Write access to the ingress-gce repo
    members:
    - aojea
    - bowei
    - DamianSawicki
    - kl52752
    - mmamczur
    - MrHohn
    - swetharepakula
    - thockin
    - TortillaZHawaii
    privacy: closed
    repos:
      ingress-gce: write
