teams:
  aws-ebs-csi-driver-admins:
    description: admin access to aws-ebs-csi-driver repo
    members:
    - AndrewSirenko
    - ConnorJC3
    - dims
    - ElijahQuinones
    - mdzraf
    - rdpsin
    - torredil
    - wongma7
    privacy: closed
    repos:
      aws-ebs-csi-driver: admin
  aws-ebs-csi-driver-maintainers:
    description: write access to aws-ebs-csi-driver repo
    members:
    - AndrewSirenko
    - bertinatto
    - ConnorJC3
    - ElijahQuinones
    - gnufied
    - jsafrane
    - mdzraf
    - rdpsin
    - torredil
    - wongma7
    privacy: closed
    repos:
      aws-ebs-csi-driver: write
  aws-encryption-provider-admins:
    description: admin access to aws_encryption-provider repo
    members:
    - dims
    - justinsb
    - micahhausler
    - nckturner
    - wongma7
    privacy: closed
    repos:
      aws-encryption-provider: admin
  aws-encryption-provider-maintainers:
    description: write access to aws_encryption-provider
    members:
    - justinsb
    - micahhausler
    - nckturner
    - wongma7
    privacy: closed
    repos:
      aws-encryption-provider: write
  aws-fsx-csi-driver-admins:
    description: admin access to aws-fsx-csi-driver
    members:
    - dims
    - khoang98
    - torredil
    privacy: closed
    repos:
      aws-fsx-csi-driver: admin
  aws-fsx-csi-driver-maintainers:
    description: write access to aws-fsx-csi-driver
    members:
    - dims
    - khoang98
    - torredil
    privacy: closed
    repos:
      aws-fsx-csi-driver: write
  aws-efs-csi-driver-admins:
    description: admin access to aws-efs-csi-driver
    members:
    - dankova22
    - DavidXU12345
    - dims
    - justinsb
    - mskanth972
    - seanzatzdev-amazon
    - torredil
    - wongma7
    privacy: closed
    repos:
      aws-efs-csi-driver: admin
  aws-efs-csi-driver-maintainers:
    description: write access to aws-efs-csi-driver
    members:
    - dankova22
    - DavidXU12345
    - jsafrane
    - justinsb
    - mskanth972
    - seanzatzdev-amazon
    - torredil
    - wongma7
    privacy: closed
    repos:
      aws-efs-csi-driver: write
